# Generated by Django 3.0 on 2020-02-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default='NULL', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(default='NULL', max_length=13),
            preserve_default=False,
        ),
    ]
